LIB_NAME    = zenonmodulo
LIB_VERSION = 0.0
LIB_FLAVOUR =
LIB_MD5     = 4cc2124741eb1c50d00319d87fc1bdb2
SYNTAX      = dk
LIB_DEPENDS = # TODO
ENCODING    = # TODO
# MAIN variable defined in 'main.mk'
.include "main.mk"

# TODO: there are too many modules in the MAIN variable,
# checking fails with
# exec(/bin/sh) failed (Argument list too long)

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
