LIB_NAME    = zenon
LIB_VERSION = 1.0
LIB_FLAVOUR =
LIB_MD5     = f3963ecd5d386a34b7d0615354c98f64
LIB_ORIGIN  = # TODO
DK_VERSION  = 2:master
MAIN        = focal

.include "${NUBOROOT}/mk/library.mk"
