LIB_NAME    = arith_fermat
LIB_VERSION = 1.0
LIB_SRC     = http://matita.cs.unibo.it/sources/matita-0.99.3.tar.gz
LIB_MD5     = aed44d9f10570f672de0224175b2b28b
ENCODING    = sttfa
PKG_URL     = http://www.lsv.fr/~hondet/logipedia/arith_fermat-1.0-sttfa.tgz
PKG_MD5     =
DK_VERSION  = 2:dc02007c095ecaa65bbcaa966402aac95071c303
TOOLING     = universo:master

.include "../../mk/library.mk"
