LIB_NAME    = arith_fermat
LIB_VERSION = 1.0
ENCODING    = sttfa
PKG_URL     = http://www.lsv.fr/~hondet/logipedia/arith_fermat-1.0-sttfa.tgz
DK_VERSION  = dc02007c095ecaa65bbcaa966402aac95071c303

.include "../../mk/library.mk"
