LIB_NAME    = focalide
LIB_VERSION = 1.0
LIB_MD5     = 81dad6d87a1de81caf2ef9754f50e1f1
LIB_ORIGIN  = # TODO
SYNTAX      = dk +cmds
TOOLING     = # TODO
LIB_DEPENDS =
ENCODING    =
MAIN        = main # TODO: many files are not typechecked

.include "${NUBOROOT}/mk/library.mk"
