LIB_NAME    = focalide
LIB_VERSION = 0.0 # TODO
LIB_MD5     = 9e5a2862183b97206f056a66e91a4bf7
LIB_ORIGIN  =  # TODO
DK_VERSION  = 2:master
TOOLING     = # TODO
LIB_DEPENDS = # TODO
ENCODING    = # TODO

.include "../../../../mk/library.mk"
