LIB_NAME    = sttfa
LIB_VERSION = 1.0
LIB_FLAVOUR =
LIB_MD5     = 96d0964282cef202d15bb2dad8dae9a5
LIB_ORIGIN  = https://github.com/Deducteam/Libraries
SYNTAX      = dk

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
