LIB_NAME    = sttfa
LIB_VERSION = 1.0
LIB_FLAVOUR =
LIB_MD5     = 01aa7f159c721e2d178b4ed780cf99b9
LIB_ORIGIN  = https://github.com/Deducteam/Libraries
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
