LIB_NAME = isabelle_base
LIB_VERSION = 1.0
LIB_MD5 = bcc1026a3858cd080fe9f1833525654d
LIB_DEPENDS =
LIB_ORIGIN = https://isabelle.in.tum.de/
ENCODING =
SYNTAX = dk
MAIN = Dedukti_Base
FLAGS = --eta

.include "${NUBOROOT}/mk/library.mk"
