LIB_NAME    = stte_hole_axioms
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = a2a492a8f5ae95326f285bedbe0d69d4
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/interoperability.tgz
LIB_DEPENDS = encodings/leibniz/sttfa,1.0 encodings/sttfa/1.0
SYNTAX      = dk

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
