LIB_NAME    = stte_hole_axioms
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 5d5ec376070804deba2384bd03b18aed
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/interoperability.tgz
LIB_DEPENDS	= encodings/leibniz/sttfa,1.0
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
