LIB_NAME    = hollight_stdlib
LIB_VERSION = 1.0
LIB_FLAVOUR	= u
LIB_MD5     = # TODO
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/hollight_stdlib_theory_u.tar.gz
DK_VERSION  = 2:DeduktiLocal
TOOLING     = hollight2dk holide dkmeta # TODO
LIB_DEPENDS = encodings/stte/u,1.0 encodings/stte_hole_axioms/u,1.0
ENCODING    = encodings/u/1.0

.include "../../../mk/library.mk"
