LIB_NAME    = stte
LIB_VERSION = 1.0
LIB_FLAVOUR = u
LIB_MD5     = 8bb34aafd689a752481cbcd34bf4cb7a
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/hollight_stdlib_theory_u.tar.gz
LIB_DEPENDS	= encodings/u/1.0
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
