LIB_NAME    = geocoq_euclid
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = b614c33e6ecf81c98a1c83c19725e716
LIB_ORIGIN  = 
SYNTAX      = dk
TOOLING     = 
LIB_DEPENDS = encodings/sttfa/1.0
ENCODING    = encodings/sttfa/1.0
MAIN        = book1

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
