LIB_NAME    = leibniz
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 2d1f321b524cfe26b4a29d56c568d2a4
LIB_ORIGIN  = https://github.com/Deducteam/Logipedia/tree/master/interoperability/hol_sttfa
LIB_DEPENDS = encodings/sttfa/1.0
SYNTAX      = dk
MAIN        = leibniz

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
