LIB_NAME    = leibniz
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = # TODO
LIB_ORIGIN  = https://github.com/Deducteam/Logipedia/tree/master/interoperability/hol_sttfa
LIB_DEPENDS	= encodings/sttfa/1.0
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
