LIB_NAME    = leibniz
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = # TODO
LIB_ORIGIN  = https://github.com/Deducteam/Logipedia/tree/master/interoperability/hol_sttfa
LIB_DEPENDS = encodings/sttfa/1.0
SYNTAX      = dk

.include "${NUBOROOT}/infrastructure/mk/library.mk"
