LIB_NAME    = sttfa
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 394e640722be57eff88aedf977834ccb
LIB_ORIGIN  = https://github.com/Deducteam/Libraries
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
