LIB_NAME    = arith_fermat
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 4730e640f18574f34dc6e46ad4721cd8
LIB_ORIGIN  = http://matita.cs.unibo.it/sources/matita-0.99.3.tar.gz
ORI_MD5     = aed44d9f10570f672de0224175b2b28b
DK_VERSION  = 2:dc02007c095ecaa65bbcaa966402aac95071c303
TOOLING     = krajono:master universo:master
LIB_DEPENDS = encodings/sttfa/1.0
ENCODING    = encdoings/sttfa/1.0

.include "../../../mk/library.mk"
