LIB_NAME    = hole
LIB_VERSION = 1.0
LIB_FLAVOUR = u
LIB_MD5     = # TODO
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/hollight_stdlib_theory_u.tgz
LIB_DEPENDS	= encodings/u/1.0
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
