LIB_NAME    = hole
LIB_VERSION = 1.0
LIB_FLAVOUR = u
LIB_MD5     = baacd6a12f08c7c877c62343781573b6
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/hollight_stdlib_theory_u.tgz
LIB_DEPENDS = encodings/u/1.0
SYNTAX      = dk

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
