LIB_NAME    = arith_fermat
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 7bf3db1bc7803349a861b206cc5619d2
LIB_ORIGIN  = http://matita.cs.unibo.it/sources/matita-0.99.3.tar.gz
ORI_MD5     = aed44d9f10570f672de0224175b2b28b
SYNTAX      = dk
TOOLING     = krajono:master universo:master
LIB_DEPENDS = encodings/sttfa/1.0
ENCODING    = encodings/sttfa/1.0
MAIN        = fermat

.include "${NUBOROOT}/mk/library.mk"
