LIB_NAME    = verine
LIB_VERSION = 1.0
LIB_MD5     = 1ddb0878145318a0b33ce095621ba161
LIB_ORIGIN  = # TODO
DK_VERSION  = 2:master
TOOLING     = # TODO
LIB_DEPENDS =
ENCODING    =
MAIN        = SEQ004_size5 \
	      SEQ004_size6 \
	      SEQ005_size7 \
	      SEQ010_size7 \
	      SEQ011_size2 \
	      SEQ011_size3 \
	      SEQ015_size2 \
	      SEQ017_size5 \
	      SEQ018_size7 \
	      SEQ019_size4 \
	      SEQ019_size5 \
	      SEQ020_size2 \
	      SEQ020_size3 \
	      SEQ032_size2 \
	      SEQ032_size3 \
	      SEQ042_size2 \
	      SEQ042_size3 \
	      SEQ050_size2 \
	      SEQ050_size3 

.include "${NUBOROOT}/mk/library.mk"
