LIB_NAME    = hollight_stdlib
LIB_VERSION = 1.0
LIB_FLAVOUR	= sttfa
LIB_MD5     = 1b9a6a0855def6aaf9323e29c7c0cebe
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/hole_stdlib.tgz
DK_VERSION  = 2:master
TOOLING     = hollight2dk holide dkmeta # TODO
LIB_DEPENDS = encodings/sttfa/1.0 encodings/stte_hole_axioms/sttfa,1.0
ENCODING    = encodings/sttfa/1.0

.include "../../../mk/library.mk"
