LIB_NAME = isabelle_export
LIB_VERSION = 1.0
LIB_MD5 = 582f74095d35d049235f74ceda39b7b6
LIB_DEPENDS =
LIB_ORIGIN = https://isabelle.in.tum.de/
ENCODING =
SYNTAX = dk
MAIN = Isabelle_Export
FLAGS = --eta

.include "${NUBOROOT}/mk/library.mk"
