LIB_NAME    = stte
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = c608ea436d2b186e2c64923480b982e3
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/interoperability.tgz
LIB_DEPENDS = encodings/sttfa/1.0
SYNTAX      = dk

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
