LIB_NAME    = stte
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = 27f2fcce7bcbcd8ea26f032593503030
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/interoperability.tgz
LIB_DEPENDS = encodings/sttfa/1.0
SYNTAX      = dk
MAIN        = stte

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
