LIB_NAME    = stte
LIB_VERSION = 1.0
LIB_FLAVOUR = sttfa
LIB_MD5     = # TODO
LIB_ORIGIN  = http://www.lsv.fr/~grienenberger/interoperability.tgz
LIB_DEPENDS	= encodings/sttfa/1.0
DK_VERSION  = 2:master

.include "../../../mk/library.mk"
