LIB_NAME    = # REQUIRED
LIB_VERSION = # REQUIRED
LIB_FLAVOUR =
LIB_MD5     = # fill with makesum
SYNTAX      =
LIB_DEPENDS = # REQUIRED (may be blank)
ENCODING    = # REQUIRED (may be blank)
MAIN        = # REQUIRED

.include "${NUBOROOT}"/infrastructure/mk/nubo.library.mk
