LIB_NAME    = iProverModulo
LIB_VERSION = 0.0 # TODO
LIB_MD5     = d3421a5eec1e0ab144f63713c9cc520a
LIB_ORIGIN  = # TODO
DK_VERSION  = 2:master
TOOLING     = # TODO
LIB_DEPENDS = # TODO
ENCODING    = # TODO

.include "../../../mk/library.mk"
