LIB_NAME    = verine
LIB_VERSION = 0.0 # TODO
LIB_MD5     = cd8a19ccbe612ebe8d712415b018709e
LIB_ORIGIN  =  # TODO
DK_VERSION  = 2:master
TOOLING     = # TODO
LIB_DEPENDS = # TODO
ENCODING    = # TODO

.include "../../../../mk/library.mk"
