name: Nubo
on: [push]
jobs:
  check-arith-fermat:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install --yes opam m4 bmake
          opam init --yes
          eval $(opam env)
          opam install dedukti.2.6.0 --yes
          eval $(opam env)
          cd libraries/arith_fermat/sttfa.1.0/ || exit 1
          NUBOROOT=${{ github.workspace }} bmake check
