name: Nubo
on: [push]
jobs:
  check-arith-fermat:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          sudo apt install --yes opam m4 bmake
          opam init --yes
          eval $(opam env)
          opam install dedukti.2.6.0 --yes
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Proof check arith_fermat-1.0-sttfa
        run: |
          eval $(opam env)
          cd 'libraries/arith_fermat/sttfa,1.0/' || exit 1
          NUBOROOT=${{ github.workspace }} bmake check
