LIB_NAME = isabelle_dk_import
LIB_VERSION = 1.0
LIB_MD5 = 019fe34fbd432adbd01b5d26bb84519f
LIB_DEPENDS =
LIB_ORIGIN = https://isabelle.in.tum.de/
ENCODING =
SYNTAX = dk
MAIN = Dedukti_Import
FLAGS = --eta

.include "${NUBOROOT}/infrastructure/mk/nubo.library.mk"
